version: "3.3"
services: 
    peaceland:
      build:
        context: /root/go/src/github.com/Peace-for-ever/peace-api
        dockerfile: /root/go/src/github.com/Peace-for-ever/peace-api/Dockerfile
      container_name: peaceland
      restart: always
      labels:
        - traefik.http.routers.peaceland.rule=Host(`peaceland.thomaslacaze.fr`)

#OR

    peaceland:
      image: thomaslacaze/peace-api:latest
      container_name: peace-api
      restart: always
      labels:
        - traefik.http.routers.peaceland.rule=Host(`peaceland.thomaslacaze.fr`)