version: "3.3"
services: 
    peaceland:
      build:
        context: /root/go/src/github.com/Peace-for-ever/peace-api
        dockerfile: /root/go/src/github.com/Peace-for-ever/peace-api/Dockerfile
      container_name: peaceland
      restart: always
      labels:
        - traefik.http.routers.peaceland.rule=Host(`peaceland.thomaslacaze.fr`)
      networks:
        - mailcow-network